redis = (loadfile "redis.lua")()
io.write("Enter TaBchi ID : ")
local last = io.read()
io.popen('rm -rf ~/.telegram-cli/TaBchi-'..last..' TaBchi-'..last..'.lua TaBchi-'..last..'.sh TaBchi_'..last..'_logs.txt')
redis:del('TaBchi:'..last..':*')
print("Done!\nAll Data/Files Of Tabchi Deleted\nTaBchi ID : "..last)
